local fm = mc.newSimpleForm()
fm.addButton('1')
fm.addButton('2')
fm.setTitle('title')
fm.setContent('content')
mc.listen("onJoin",function (player)
    player.sendForm(fm,function (player, id)
        logger.info('player '..player.name..' clickid is'..id)
        player.tell('you is mine')
    end)
end)